SELECT *
FROM financials
LIMIT 15;

CREATE TABLE staging
AS SELECT *
FROM financials;

SELECT *
FROM staging;

SET SQL_SAFE_UPDATES = 0;

SELECT DISTINCT *
FROM STAGING;

-- UNITS SOLD SHOULDNT BE IN DOLLARS

UPDATE STAGING
SET `UNITS SOLD` = REPLACE(`UNITS SOLD`, '$', ''),
`UNITS SOLD` = REPLACE(`UNITS SOLD`, ',', ''),
`UNITS SOLD` = REPLACE(`UNITS SOLD`, '.00', ''),
`UNITS SOLD` = REPLACE(`UNITS SOLD`, '.50', '');

ALTER TABLE STAGING
MODIFY COLUMN `UNITS SOLD` INT;

ALTER TABLE STAGING
RENAME COLUMN `UNITS SOLD` TO `UnitSold`;

DESCRIBE STAGING;

-- CHECK IF COUNTRIES HAVE ANY ISSUES

SELECT REPLACE(`DISCOUNTS`, '$-', '0.00')
FROM STAGING;

SELECT *
FROM STAGING;

-- FIX DISCOUNTS AREA

UPDATE STAGING
SET `DISCOUNTS` = REPLACE(`DISCOUNTS`, '$-', '0.00'),
	`DISCOUNTS` = REPLACE(`DISCOUNTS`, '$',''),
    `DISCOUNTS` = REPLACE(`DISCOUNTS`, ',', '');
    
    
ALTER TABLE STAGING
MODIFY COLUMN `DISCOUNTS` DECIMAL(10,2);

UPDATE STAGING
SET `SALE PRICE` = REPLACE(`SALE PRICE`, '$', '');


UPDATE STAGING
SET `MANUFACTURING PRICE` = REPLACE(`MANUFACTURING PRICE`, '$', ''),
	`SALES` = REPLACE(`SALES`, '$', ''),
    `SALES` = REPLACE(`SALES`, ',', ''),
    `GROSS SALES` = REPLACE(`GROSS SALES`, '$', ''),
    `GROSS SALES` = REPLACE(`GROSS SALES`, ',', ''),
    `COGS` = REPLACE(`COGS`, '$', ''),
    `COGS` = REPLACE(`COGS`, ',', ''),
    `PROFIT` = REPLACE(`PROFIT`, '$',''),
    `PROFIT` = REPLACE(`PROFIT`, ',','');

UPDATE STAGING
SET `PROFIT`= CASE WHEN `PROFIT` LIKE '%-%' THEN '0.00' ELSE `PROFIT` END;

UPDATE STAGING
SET `MANUFACTURING PRICE` = TRIM(`MANUFACTURING PRICE`),
	`SALES` = TRIM(`SALES`),
	`GROSS SALES` = TRIM(`GROSS SALES`),
    `COGS` = TRIM(`COGS`),
    `PROFIT` = TRIM(`PROFIT`);
    
UPDATE STAGING
SET `PROFIT` = REPLACE(`PROFIT`, '(','-'),
`PROFIT` = REPLACE(`PROFIT`, ')','');


ALTER TABLE STAGING
MODIFY COLUMN `MANUFACTURING PRICE` DECIMAL(25,2),
MODIFY COLUMN `SALE PRICE` DECIMAL(25,2),
MODIFY COLUMN `GROSS SALES` DECIMAL(25,2),
MODIFY COLUMN `SALES` DECIMAL(25,2),
MODIFY COLUMN `COGS` DECIMAL(25,2),
MODIFY COLUMN `PROFIT` DECIMAL(25,2);

DESCRIBE STAGING;

SELECT *
FROM STAGING;

SELECT `DATE`, STR_TO_DATE(`DATE`, '%m/%d/%Y') AS DATE_UPDATE
FROM STAGING;

UPDATE STAGING
SET `DATE` = STR_TO_DATE(`DATE`, '%m/%d/%Y');

ALTER TABLE STAGING
RENAME COLUMN `DISCOUNT BAND` TO `DiscountBand`,
RENAME COLUMN `MANUFACTURING PRICE` TO `ManufacturingPrice`,
RENAME COLUMN `SALE PRICE` TO `SalePrice`,
RENAME COLUMN `GROSS SALES` TO `GrossSales`,
RENAME COLUMN `DISCOUNTS` TO `Discounts`,
RENAME COLUMN `SALES` TO `Sales`,
RENAME COLUMN `MONTH NUMBER` TO `MonthNo`,
RENAME COLUMN `MONTH NAME` TO `MonthNm`;

ALTER TABLE STAGING
RENAME COLUMN `PROFIT` TO `Profit`;

-- LETS DO SOME QUERIES NOW

# WHAT IS THE TOTAL PROFIT FOR EACH YEAR?
SELECT SUM(`PROFIT`), `YEAR`
FROM STAGING
GROUP BY `YEAR`
ORDER BY `YEAR` DESC;

# HOW MANY UNITS WERE SOLD PER PRODUCT?
SELECT SUM(`UNITSOLD`) AS TotalUnitSold, `PRODUCT`
FROM STAGING
GROUP BY `PRODUCT`;

# WHAT IS THE AVG DISCOUNT PER SEGMENT?
SELECT `Segment`, ROUND(AVG(`DISCOUNTS`),2) AS AvgDiscount
FROM STAGING
GROUP BY `SEGMENT`;

# WHAT IS THE TOTAL SALES BY COUNTRY?
SELECT `COUNTRY`, SUM(`SALES`) AS TotalSales 
FROM STAGING
GROUP BY `COUNTRY`;

# WHAT IS THE MONTHLY SALES TREND FOR THE 2014 YEAR?
SELECT `MONTHNO`, `MONTHNM`, SUM(`SALES`) AS TotalSales
FROM STAGING
WHERE `Year` = 2014
GROUP BY `MONTHNO`, `MONTHNM`
ORDER BY `MONTHNO`;

# WHICH MONTH HAS THE HIGHEST COGS IN 2013?
SELECT `MONTHNO`, `MONTHNM`, SUM(COGS) AS TotalCOGS
FROM STAGING
WHERE `YEAR`= 2013
GROUP BY `MONTHNO`, `MONTHNM`
ORDER BY TotalCOGS DESC
LIMIT 1;

# WHAT IS THE YEAR OVER YEAR PROFIT GROWTH?
WITH TEMP AS (SELECT `YEAR`, SUM(`PROFIT`) AS TotalProfit
	FROM STAGING
	GROUP BY `YEAR`)
SELECT ROUND((`TotalProfit` - LAG(`TotalProfit`) OVER (ORDER BY `YEAR`))/LAG(`TotalProfit`) OVER (ORDER BY `YEAR`),2) AS YoYGrowth, `YEAR`
FROM TEMP;

# SHOW SALES WHERE DISCOUNT IS GREATER THAN 10%
WITH TEMP AS (SELECT *, ROUND((`DISCOUNTS`/`GROSSSALES`) * 100,2) AS DiscPercent 
			  FROM STAGING)
SELECT `SEGMENT`, `COUNTRY`, `PRODUCT`, `SALES`, `DISCPERCENT`
FROM TEMP
WHERE `DISCPERCENT` >= 10;

# WHICH PRODUCTS HAD SALES ABOVE 1,000,000 IN ANY GIVEN MONTH
SELECT SUM(`SALES`) AS TotalSales, `PRODUCT`, `MONTHNM`, `MONTHNO`, `YEAR`
FROM STAGING
WHERE `MONTHNO` = 6 AND `YEAR` = 2014
GROUP BY `PRODUCT`, `MONTHNM`, `MONTHNO`, `YEAR`
HAVING SUM(`SALES`) > 1000000;

# WHAT IS THE TOTAL GROSS SALES PER DISCOUNT BAND
SELECT SUM(`GROSSSALES`) AS TotalGSales, `DISCOUNTBAND`
FROM STAGING
GROUP BY `DISCOUNTBAND`
ORDER BY TotalGSales;

# SHOW COGS PER SEGMENT AND YEAR
SELECT SUM(`COGS`) AS TotalCOGS, `SEGMENT`, `YEAR`
FROM STAGING
GROUP BY `YEAR`,`SEGMENT`
ORDER BY TotalCOGS;

# WHICH PRODUCT HAS THE HIGHEST PROFIT MARGIN?
SELECT `PRODUCT`, SUM(`PROFIT`)/SUM(`SALES`) AS HPM
FROM STAGING
GROUP BY `PRODUCT`
ORDER BY HPM DESC
LIMIT 1;

# WHAT IS THE MOST SOLD PRODUCT IN EACH SEGMENT
SELECT `SEGMENT`, `PRODUCT`, SUM(`UNITSOLD`) AS MostSold
FROM STAGING
GROUP BY `SEGMENT`, `PRODUCT`
ORDER BY MostSold DESC
LIMIT 1;

# COMPARE SALES BETWEEN SMALL BUSINESS AND ENTERPRISES
SELECT `SEGMENT`, SUM(`SALES`) AS TotalSales
FROM STAGING
WHERE `SEGMENT` = 'Small Business' OR `SEGMENT` = 'Enterprise'
GROUP BY SEGMENT;

# CREATE PROFIT MARGIN FOR EACH ROW
SELECT *, ROUND((`PROFIT`/`SALES`) * 100, 2) AS ProfitMargin 
FROM STAGING;

# WHAT IS THE TOTAL DISCOUNT GIVEN PER COUNTRY
SELECT `COUNTRY`, SUM(`DISCOUNTS`) AS TotalDisc
FROM STAGING
GROUP BY `COUNTRY`;

# WHICH COUNTRY HAD THE HIGHEST AVERAGE SALE PRICE
SELECT `COUNTRY`, ROUND(AVG(`SALEPRICE`),2) AS AvgSP
FROM STAGING
GROUP BY `COUNTRY`;

# WHAT ARE  TOP 3 COUNTRIES BY PROFIT?
SELECT SUM(`PROFIT`) AS TotalProfit, `COUNTRY`
FROM STAGING
GROUP BY `COUNTRY`
ORDER BY TotalProfit DESC
LIMIT 3;

# FIND THE FIRST AND LAST SALE DATE PER PRODUCT
SELECT `PRODUCT`, MIN(`DATE`) AS `FIRST`, MAX(`DATE`) AS `LAST`
FROM STAGING
GROUP BY `PRODUCT`;

# RANK COUNTRIES BY SALES IN EACH YEAR
SELECT `COUNTRY`, SUM(`SALES`) AS TotalSales, `YEAR`
FROM STAGING
WHERE `YEAR` = 2014
GROUP BY `COUNTRY`
ORDER BY TotalSales;

# IDENTIFY THE MONTH WITH THE LARGEST INCREASE IN PROFIT MONTH OVER MONTH
WITH TEMP AS (SELECT `MONTHNO`, SUM(`PROFIT`) AS TP
	FROM STAGING
	WHERE `YEAR` = 2014
	GROUP BY `MONTHNO`
	ORDER BY `MONTHNO`)
SELECT `MONTHNO`, ROUND((TP - LAG(TP) OVER (ORDER BY `MONTHNO`)) / LAG(TP) OVER (ORDER BY `MONTHNO`), 2) AS MoM
FROM TEMP;

